### ISSUE TITLE
Release phar

### ISSUE THREAD

**Issue by mathewpeterson** [code-drop/Circle-CLI#1]
It would be nice if would be released as a phar file so we don't have conflicting global dependencies. See http://box-project.org/ for more info.

Please let me know if there's anything I can help with.

**Comment by benjy** [comment]
Yeah definitely, I already had that down in the TODO in the README.

Give me a few days and i'll sort it out.

**Comment by benjy** [comment]
OK released an initial phar file available here: https://code-drop.github.io/Circle-CLI/circle-cli.phar

I've also added it to the README instructions. Not sure if we need self-update in the future but that can come later.
